// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnkA4bKsGmzSzyH0LvKphF4cryHD6gwi8',
    appId: '1:483803846444:web:de910f4bdc8cd55623be89',
    messagingSenderId: '483803846444',
    projectId: 'chatee-privatechat',
    authDomain: 'chatee-privatechat.firebaseapp.com',
    storageBucket: 'chatee-privatechat.appspot.com',
    measurementId: 'G-Y5KHWWZV1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbFA_gRPwmudkHMgWRF_dFsX1w6Vy1YPQ',
    appId: '1:483803846444:android:f910ff28956a973123be89',
    messagingSenderId: '483803846444',
    projectId: 'chatee-privatechat',
    storageBucket: 'chatee-privatechat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFHHVi7hChIY9Vh6pZa3qMeS5Qfry4_E',
    appId: '1:483803846444:ios:6fca9a97a00b512123be89',
    messagingSenderId: '483803846444',
    projectId: 'chatee-privatechat',
    storageBucket: 'chatee-privatechat.appspot.com',
    iosClientId: '483803846444-19cme9ildpmkoo10bgetocst94gacqu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUFHHVi7hChIY9Vh6pZa3qMeS5Qfry4_E',
    appId: '1:483803846444:ios:9dcbdec611c73a4d23be89',
    messagingSenderId: '483803846444',
    projectId: 'chatee-privatechat',
    storageBucket: 'chatee-privatechat.appspot.com',
    iosClientId: '483803846444-lj0hkvor9g3a6ctrg8qol9fvtahs4d83.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatee.RunnerTests',
  );
}
