// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9N3A8W6g-ThwdeHqIn4GBkuzERxnbl94',
    appId: '1:664142919571:web:095ed842fadf17c14b9a66',
    messagingSenderId: '664142919571',
    projectId: 'private-room-chate',
    authDomain: 'private-room-chate.firebaseapp.com',
    storageBucket: 'private-room-chate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0bxqnVPwZJEcd1JqoW5NZELHqEffPPA',
    appId: '1:664142919571:android:0add5846fa2d112d4b9a66',
    messagingSenderId: '664142919571',
    projectId: 'private-room-chate',
    storageBucket: 'private-room-chate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbr1y1sxJhafBV5Q_V7DiX3CCdHga0-8',
    appId: '1:664142919571:ios:8bb83cef07c8c44f4b9a66',
    messagingSenderId: '664142919571',
    projectId: 'private-room-chate',
    storageBucket: 'private-room-chate.appspot.com',
    iosClientId: '664142919571-hp0s8ij2tunco946uaa027jgdt3fdr54.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbr1y1sxJhafBV5Q_V7DiX3CCdHga0-8',
    appId: '1:664142919571:ios:e4fdf0bb5d3853bf4b9a66',
    messagingSenderId: '664142919571',
    projectId: 'private-room-chate',
    storageBucket: 'private-room-chate.appspot.com',
    iosClientId: '664142919571-8ll02gt83knikhghuu9l424b5g6tib15.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatee.RunnerTests',
  );
}
